# Generated by tools/update_public_msg_snapshot.exs
# Public fixtures only. Do not place private message content in this file.

%{
  "Swetlana Novikova.msg" => %{
  subject: "Swetlana Novikova",
  recipient_count: 0,
  attachment_count: 0,
  first_recipient_email: "",
  body_len: 0,
  html_len: 0,
  body_sha256: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
  html_sha256: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
},
  "contact-plain.msg" => %{
  subject: "(full name) A completely bogus contact",
  recipient_count: 0,
  attachment_count: 0,
  first_recipient_email: "",
  body_len: 0,
  html_len: 0,
  body_sha256: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
  html_sha256: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
},
  "contact-unicode.msg" => %{
  subject: "(full name) A completely bogus contact",
  recipient_count: 0,
  attachment_count: 0,
  first_recipient_email: "",
  body_len: 0,
  html_len: 0,
  body_sha256: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
  html_sha256: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
},
  "note.msg" => %{
  subject: "note sample",
  recipient_count: 0,
  attachment_count: 0,
  first_recipient_email: "",
  body_len: 57,
  html_len: 0,
  body_sha256: "7f58bae8d2b3cdc0030bd83621107252d0815a62fb120a73d71af821b218efd9",
  html_sha256: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
},
  "qwerty_1-orig.msg" => %{
  subject: "qwerty",
  recipient_count: 1,
  attachment_count: 0,
  first_recipient_email: "",
  body_len: 143,
  html_len: 569,
  body_sha256: "952d5d8aa11e084a89baee91576c774355196c3ec8859e3c97d5ece59d130561",
  html_sha256: "6a35062b2273b6964cf73f3ac67691da5f562626f49ea264e94b1f781ac62301"
},
  "qwerty_2-with_custom_properties.msg" => %{
  subject: "qwerty",
  recipient_count: 3,
  attachment_count: 0,
  first_recipient_email: "",
  body_len: 143,
  html_len: 569,
  body_sha256: "952d5d8aa11e084a89baee91576c774355196c3ec8859e3c97d5ece59d130561",
  html_sha256: "6a35062b2273b6964cf73f3ac67691da5f562626f49ea264e94b1f781ac62301"
},
  "qwerty_3.msg" => %{
  subject: "qwerty",
  recipient_count: 3,
  attachment_count: 0,
  first_recipient_email: "",
  body_len: 143,
  html_len: 569,
  body_sha256: "952d5d8aa11e084a89baee91576c774355196c3ec8859e3c97d5ece59d130561",
  html_sha256: "6a35062b2273b6964cf73f3ac67691da5f562626f49ea264e94b1f781ac62301"
},
  "test_Blammo.msg" => %{
  subject: "BlammoBlammo",
  recipient_count: 0,
  attachment_count: 0,
  first_recipient_email: "",
  body_len: 8,
  html_len: 1471,
  body_sha256: "73f82639a8437f7b51cde7ceee5b503f4b4683361178116e23eb71799a702911",
  html_sha256: "50a2b4778c4c7ea6b32b7b3356d17900cd9c4652187984e64efd9b7b67a329d0"
}
}
